# Statistics

### Measures of center
        1. Mean
        2. Median
        3. Mode

In [1]:
import numpy as np

In [3]:
ages = list(np.random.randint(19, 25, 100))
print(ages)

[21, 21, 22, 20, 23, 23, 20, 23, 21, 21, 20, 22, 24, 23, 24, 19, 22, 21, 24, 24, 23, 22, 22, 20, 21, 22, 22, 22, 22, 24, 24, 22, 23, 19, 19, 20, 19, 20, 22, 21, 21, 23, 20, 19, 24, 19, 21, 21, 24, 21, 22, 19, 21, 24, 23, 20, 24, 22, 19, 23, 19, 24, 24, 23, 20, 21, 19, 20, 24, 21, 22, 23, 22, 24, 24, 24, 22, 20, 24, 20, 24, 23, 19, 24, 23, 19, 21, 21, 20, 23, 24, 22, 23, 23, 19, 23, 24, 19, 23, 21]


In [4]:
sum(ages) / len(ages)

21.75

In [7]:
mean = np.mean(ages)
mean

21.75

In [8]:
median = np.median(ages)
median

22.0

In [9]:
print("Without Outlier")
print(f"Mean: {mean}")
print(f"Median: {median}")


Without Outlier
Mean: 21.75
Median: 22.0


In [10]:
print(ages)

[21, 21, 22, 20, 23, 23, 20, 23, 21, 21, 20, 22, 24, 23, 24, 19, 22, 21, 24, 24, 23, 22, 22, 20, 21, 22, 22, 22, 22, 24, 24, 22, 23, 19, 19, 20, 19, 20, 22, 21, 21, 23, 20, 19, 24, 19, 21, 21, 24, 21, 22, 19, 21, 24, 23, 20, 24, 22, 19, 23, 19, 24, 24, 23, 20, 21, 19, 20, 24, 21, 22, 23, 22, 24, 24, 24, 22, 20, 24, 20, 24, 23, 19, 24, 23, 19, 21, 21, 20, 23, 24, 22, 23, 23, 19, 23, 24, 19, 23, 21]


In [11]:
new_student = [65,70,45,55,67,78,56,77,87,87]

In [12]:
ages.extend(new_student)

In [13]:
print(ages)

[21, 21, 22, 20, 23, 23, 20, 23, 21, 21, 20, 22, 24, 23, 24, 19, 22, 21, 24, 24, 23, 22, 22, 20, 21, 22, 22, 22, 22, 24, 24, 22, 23, 19, 19, 20, 19, 20, 22, 21, 21, 23, 20, 19, 24, 19, 21, 21, 24, 21, 22, 19, 21, 24, 23, 20, 24, 22, 19, 23, 19, 24, 24, 23, 20, 21, 19, 20, 24, 21, 22, 23, 22, 24, 24, 24, 22, 20, 24, 20, 24, 23, 19, 24, 23, 19, 21, 21, 20, 23, 24, 22, 23, 23, 19, 23, 24, 19, 23, 21, 65, 70, 45, 55, 67, 78, 56, 77, 87, 87]


In [14]:
print("With Outlier")
print(f"Mean: {np.mean(ages)}")
print(f"Median: {np.median(ages)}")


With Outlier
Mean: 26.01818181818182
Median: 22.0


In [16]:
country = np.random.choice(['aus', 'india', 'china', 'usa'], 100)
country

array(['china', 'india', 'aus', 'aus', 'india', 'india', 'china', 'china',
       'usa', 'india', 'india', 'usa', 'aus', 'aus', 'usa', 'china',
       'usa', 'india', 'aus', 'india', 'usa', 'india', 'india', 'usa',
       'china', 'china', 'aus', 'aus', 'aus', 'usa', 'india', 'aus',
       'china', 'aus', 'aus', 'usa', 'china', 'india', 'india', 'aus',
       'india', 'india', 'india', 'china', 'china', 'india', 'india',
       'usa', 'china', 'china', 'china', 'aus', 'china', 'usa', 'china',
       'usa', 'aus', 'aus', 'usa', 'aus', 'usa', 'india', 'usa', 'usa',
       'china', 'india', 'china', 'usa', 'india', 'china', 'aus', 'aus',
       'usa', 'aus', 'aus', 'aus', 'aus', 'china', 'usa', 'aus', 'china',
       'india', 'usa', 'aus', 'aus', 'usa', 'usa', 'india', 'india',
       'usa', 'india', 'aus', 'china', 'china', 'india', 'aus', 'aus',
       'aus', 'china', 'india'], dtype='<U5')

In [17]:
data = {}

for i in country:
    if i in data:
        data[i] += 1
    else:
        data[i] = 1
print(data)

{'china': 23, 'india': 26, 'aus': 29, 'usa': 22}


In [19]:
data

{'china': 23, 'india': 26, 'aus': 29, 'usa': 22}

In [20]:
data.items()

dict_items([('china', 23), ('india', 26), ('aus', 29), ('usa', 22)])

In [24]:
m = max(list(data.values()))
m

29

In [21]:
for i,j in data.items():
    print(i)

('china', 23)
('india', 26)
('aus', 29)
('usa', 22)


In [25]:
for i,j in data.items():
    if j == m:
        print(i)

aus


In [1]:
import numpy as np

In [3]:
arr = np.array([10,20,30,40,50])
arr

array([10, 20, 30, 40, 50])

In [ ]:
arr.ndim # TELL THE TYPE OF ARRAY

1

In [ ]:
arr.shape  # 1Darray = (element, ) comma is there because only one dimension is there

(5,)

In [6]:
arr.size

5

In [7]:
arr.dtype

dtype('int32')

In [31]:
arr

array([10, 20, 30, 40, 50])

In [8]:
arr[0]

10

In [9]:
arr[-2]

40

In [10]:
arr

array([10, 20, 30, 40, 50])

In [ ]:
arr[:3] #pehle

array([10, 20, 30])

In [12]:
arr

array([10, 20, 30, 40, 50])

In [13]:
arr[0] = 100

In [14]:
arr

array([100,  20,  30,  40,  50])

In [15]:
arr[:3] = 20

In [16]:
arr

array([20, 20, 20, 40, 50])

In [17]:
arr

array([20, 20, 20, 40, 50])

In [18]:
arr + 10

array([30, 30, 30, 50, 60])

In [19]:
arr / 10


array([2., 2., 2., 4., 5.])

In [20]:
arr * 10

array([200, 200, 200, 400, 500])

In [46]:
arr

array([20, 20, 20, 40, 50])

In [21]:
arr[0]

20

In [23]:
arr[[1,4,0]]

array([20, 50, 20])

In [24]:
arr

array([20, 20, 20, 40, 50])

#### boolean index

In [30]:
arr

array([20, 20, 20, 40, 50])

In [25]:
arr[[True, False, False, True, False]]

array([20, 40])

In [26]:
arr

array([20, 20, 20, 40, 50])

In [31]:
arr < 30

array([ True,  True,  True, False, False])

In [32]:
arr[arr < 30]


array([20, 20, 20])

In [33]:
arr

array([20, 20, 20, 40, 50])

In [34]:
(arr < 30) | (arr > 40)

array([ True,  True,  True, False,  True])

In [ ]:
arr[(arr < 30) | (arr > 40)]   # inner bracket is used for condition, outer bracket is used for values select karna ka liya


array([20, 20, 20, 50])

In [36]:
arr

array([20, 20, 20, 40, 50])

In [37]:
np.mean(arr)

30.0

In [38]:
arr

array([20, 20, 20, 40, 50])

In [39]:
arr.mean()

30.0

In [40]:
arr.sum()

150

In [41]:
arr.min()

20

In [42]:
arr.max()

50

In [43]:
arr

array([20, 20, 20, 40, 50])

In [ ]:
arr.cumsum() # it is use for calculat the sum

array([ 20,  40,  60, 100, 150])

In [ ]:
arr.cumprod()  # it is use for calculat the product

array([      20,      400,     8000,   320000, 16000000])

In [64]:
[[10,20,30], [30,40,50], [56,78,89]]

[[10, 20, 30], [30, 40, 50], [56, 78, 89]]

In [47]:
arr_2d = np.array([[10,20,30], [30,40,50], [56,78,89]])
arr_2d

array([[10, 20, 30],
       [30, 40, 50],
       [56, 78, 89]])

In [ ]:
arr_2d.ndim  # ndim is used for dimensions

2

In [49]:
arr_2d.shape

(3, 3)

In [50]:
arr_2d.size

9

In [ ]:
len(arr_2d)  # tell the no of rows

3

In [52]:
arr_2d

array([[10, 20, 30],
       [30, 40, 50],
       [56, 78, 89]])

In [ ]:
arr_2d[0]  # bracket is used for taking the index

array([10, 20, 30])

In [54]:
arr_2d[1]

array([30, 40, 50])

In [55]:
arr_2d[2]

array([56, 78, 89])

In [56]:

arr_2d

array([[10, 20, 30],
       [30, 40, 50],
       [56, 78, 89]])

In [57]:
arr_2d[1]

array([30, 40, 50])

In [58]:
arr_2d[1, 2]


50

In [59]:
arr_2d

array([[10, 20, 30],
       [30, 40, 50],
       [56, 78, 89]])

### slicing on 2-D array

        syntax:
                arr[row_slicing, col_slicing]

In [ ]:
arr_2d[1:, 1:]  # in slicing first index and last index is not used

array([[40, 50],
       [78, 89]])

In [61]:
arr_2d

array([[10, 20, 30],
       [30, 40, 50],
       [56, 78, 89]])

In [ ]:
arr_2d[:, ::2] # first colon is used for taking all the rows and third colon is used for  2nd column select karta ha

array([[10, 30],
       [30, 50],
       [56, 89]])

In [63]:
arr_2d

array([[10, 20, 30],
       [30, 40, 50],
       [56, 78, 89]])

In [64]:
arr_2d + 10

array([[20, 30, 40],
       [40, 50, 60],
       [66, 88, 99]])

In [65]:
arr_2d / 10

array([[1. , 2. , 3. ],
       [3. , 4. , 5. ],
       [5.6, 7.8, 8.9]])

In [66]:
arr_2d

array([[10, 20, 30],
       [30, 40, 50],
       [56, 78, 89]])

In [67]:
arr_2d < 50

array([[ True,  True,  True],
       [ True,  True, False],
       [False, False, False]])

In [68]:
arr_2d[arr_2d < 50]


array([10, 20, 30, 30, 40])

In [70]:
arr_2d.mean()

44.77777777777778

In [71]:
arr_2d

array([[10, 20, 30],
       [30, 40, 50],
       [56, 78, 89]])

In [75]:
#                 p   c   m
data = np.array([[10, 20, 30], #s1
          [30, 40, 50], #s2
          [56, 78, 89]] #s3
        )

In [76]:
data

array([[10, 20, 30],
       [30, 40, 50],
       [56, 78, 89]])

In [77]:
data.mean()

44.77777777777778

In [ ]:
data.mean(axis=0)  # har column ka average mean nikalna ka liya 
                   # axis = 0 = column wise calculation
                   # data ko table ki tarah treat karta ha

array([32.        , 46.        , 56.33333333])

In [ ]:
data.mean(axis=1) # har row ka average (mean)


array([20.        , 40.        , 74.33333333])

In [80]:
arr_2d

array([[10, 20, 30],
       [30, 40, 50],
       [56, 78, 89]])

In [81]:
arr_2d.sum()

403

In [ ]:
arr_2d.sum(axis=1) # har row ka sum alag alag liya ha

array([ 60, 120, 223])

In [83]:
arr_2d.min()

10

In [ ]:
arr_2d.min(axis=1) # har row sa sabse chotta number

array([10, 30, 56])

In [85]:
arr

array([20, 20, 20, 40, 50])

In [86]:
arr_2d

array([[10, 20, 30],
       [30, 40, 50],
       [56, 78, 89]])

In [88]:
%%writefile data.csv
price,selling_price,quantity
3400,4000,9
4500,6000,6
3000,5000,4
2300,4000,6

Writing data.csv


In [ ]:
#csv file ko NumPy 2D array mein read kiya 
# skip_header = 1 -> column names skip kar do
# delimeter = ',' -> comma sa data alag
# missing value -> nan
# data analysis ke liya ready

In [92]:
data = np.genfromtxt('data.csv', delimiter=',', skip_header=1)
data

array([[3.4e+03, 4.0e+03, 9.0e+00],
       [4.5e+03, 6.0e+03, 6.0e+00],
       [3.0e+03, 5.0e+03, 4.0e+00],
       [2.3e+03, 4.0e+03, 6.0e+00]])

In [96]:
price = data[:, 0]
selling_price = data[:, 1]
quantity = data[:, 2]

In [ ]:
(selling_price - price) * qunatity  # profit calculate kiya ha

array([ 5400.,  9000.,  8000., 10200.])

In [ ]:
((selling_price - price) * qunatity).sum() # toatal profit nikala


32600.0

In [99]:
arr_3d = np.array([
    [
        [10,20,30],
        [40,50,60]
    ],
    [
        [40,50,60],
        [34,56,68],
    ],
    [
        [23,45,67],
        [12,34,56]
    ]
])

In [100]:
arr_3d

array([[[10, 20, 30],
        [40, 50, 60]],

       [[40, 50, 60],
        [34, 56, 68]],

       [[23, 45, 67],
        [12, 34, 56]]])

In [101]:
arr_3d.ndim

3

In [102]:
arr_3d.shape

(3, 2, 3)

In [103]:
arr_3d

array([[[10, 20, 30],
        [40, 50, 60]],

       [[40, 50, 60],
        [34, 56, 68]],

       [[23, 45, 67],
        [12, 34, 56]]])

In [104]:
arr_3d[0]

array([[10, 20, 30],
       [40, 50, 60]])

In [105]:
arr_3d[-1]

array([[23, 45, 67],
       [12, 34, 56]])

In [106]:
arr_3d

array([[[10, 20, 30],
        [40, 50, 60]],

       [[40, 50, 60],
        [34, 56, 68]],

       [[23, 45, 67],
        [12, 34, 56]]])

In [ ]:
arr_3d[1, 1, 2] # 1-> 2nd block, 1-> us block 2nd row , 2-> us row ka 3rd column

68

#### slicing on 3-D array

    syntax:
                arr[2_d slicing, row_slicing, col_slicing]

In [108]:
arr_3d

array([[[10, 20, 30],
        [40, 50, 60]],

       [[40, 50, 60],
        [34, 56, 68]],

       [[23, 45, 67],
        [12, 34, 56]]])

In [ ]:
arr_3d[1:, :2, 1:]  # 1: -> first block skip , : -> all rows , 1: -> first col skip

array([[[50, 60],
        [56, 68]],

       [[45, 67],
        [34, 56]]])

In [110]:
arr_2d

array([[10, 20, 30],
       [30, 40, 50],
       [56, 78, 89]])

In [ ]:
arr  # 1d array

array([20, 20, 20, 40, 50])

In [ ]:
# slicing format : arr[start:end:step]
# : -> end sa start 
# : -> start tak
# -1 -> step  

In [112]:
arr[::-1]

array([50, 40, 20, 20, 20])

In [113]:
arr_2d

array([[10, 20, 30],
       [30, 40, 50],
       [56, 78, 89]])

In [ ]:
arr_2d[::-1]
# : end sa start
# : start tak
# -1 step

array([[56, 78, 89],
       [30, 40, 50],
       [10, 20, 30]])

In [ ]:
arr_2d[::-1, ::-1]
# ::-1 -> pehla row reverse 
# ::-1 -> coulmn reverse

array([[89, 78, 56],
       [50, 40, 30],
       [30, 20, 10]])

In [116]:
arr_2d

array([[10, 20, 30],
       [30, 40, 50],
       [56, 78, 89]])

In [ ]:
range()

In [117]:
np.arange(1, 21)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [118]:
np.arange(0.1, 1.1, 0.1)


array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [ ]:
np.linspace(1, 100, 100)  #linearly spaced values

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])

In [ ]:
np.linspace(1, 100, 50) # 1 to 100 ke between 50 equally spaced values
                        # (100-1)/(50-1)=2.02

array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
         9.08163265,  11.10204082,  13.12244898,  15.14285714,
        17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
        25.24489796,  27.26530612,  29.28571429,  31.30612245,
        33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
        41.40816327,  43.42857143,  45.44897959,  47.46938776,
        49.48979592,  51.51020408,  53.53061224,  55.55102041,
        57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
        65.65306122,  67.67346939,  69.69387755,  71.71428571,
        73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
        81.81632653,  83.83673469,  85.85714286,  87.87755102,
        89.89795918,  91.91836735,  93.93877551,  95.95918367,
        97.97959184, 100.        ])

In [ ]:
np.linspace(1, 10, 100)  # start =1 , end = 10, total values = 100
                         # (10-1)/(100-1)=0.0909

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [123]:
arr = np.arange(1, 21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [124]:
arr.reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [125]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
arr.reshape(2,2,5)
# 2 blocks ; 2 rows ; 5 column

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [127]:
arr_2d

array([[10, 20, 30],
       [30, 40, 50],
       [56, 78, 89]])

In [ ]:
arr_2d.flatten() # convert 2D array to 1D array

array([10, 20, 30, 30, 40, 50, 56, 78, 89])

In [129]:
arr_3d

array([[[10, 20, 30],
        [40, 50, 60]],

       [[40, 50, 60],
        [34, 56, 68]],

       [[23, 45, 67],
        [12, 34, 56]]])

In [ ]:
arr_3d.flatten() # convert 3D array to 1D array

array([10, 20, 30, 40, 50, 60, 40, 50, 60, 34, 56, 68, 23, 45, 67, 12, 34,
       56])

In [132]:
arr_2d

array([[10, 20, 30],
       [30, 40, 50],
       [56, 78, 89]])

In [133]:
arr_2d.transpose()

array([[10, 30, 56],
       [20, 40, 78],
       [30, 50, 89]])

#### matrix multiplication

In [134]:
arr_2d

array([[10, 20, 30],
       [30, 40, 50],
       [56, 78, 89]])

In [ ]:
arr1 = np.arange(1,21).reshape(4,5)   # 1 to 20 tak numbers and reshape 4 rows and 5 column
arr2 = np.arange(21, 41).reshape(4,5)

In [137]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [139]:
arr2

array([[21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40]])

In [140]:
arr1 + arr2

array([[22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50],
       [52, 54, 56, 58, 60]])

In [141]:
arr1 / arr2

array([[0.04761905, 0.09090909, 0.13043478, 0.16666667, 0.2       ],
       [0.23076923, 0.25925926, 0.28571429, 0.31034483, 0.33333333],
       [0.35483871, 0.375     , 0.39393939, 0.41176471, 0.42857143],
       [0.44444444, 0.45945946, 0.47368421, 0.48717949, 0.5       ]])

In [142]:
arr1 * arr2

array([[ 21,  44,  69,  96, 125],
       [156, 189, 224, 261, 300],
       [341, 384, 429, 476, 525],
       [576, 629, 684, 741, 800]])

In [143]:
arr1 = np.array([
    [2,3],
    [4,5]
])

arr2 = np.array([
    [3,4,5],
    [4,5,6]
])

In [144]:
arr1

array([[2, 3],
       [4, 5]])

In [145]:
arr2

array([[3, 4, 5],
       [4, 5, 6]])

In [146]:
arr * arr2

ValueError: operands could not be broadcast together with shapes (20,) (2,3) 

In [147]:
arr1

array([[2, 3],
       [4, 5]])

In [ ]:
arr2

array([[3, 4, 5],
       [4, 5, 6]])

Matrix multiplication


In [ ]:
# matrix multiplication
np.matmul(arr1, arr2)

array([[18, 23, 28],
       [32, 41, 50]])

In [ ]:
arr1@arr2  # shortcut way for the multiplication

array([[18, 23, 28],
       [32, 41, 50]])

In [151]:
arr1.dot(arr2)

array([[18, 23, 28],
       [32, 41, 50]])

In [ ]:
# np = numpy module
# dir(np) -> numpy module ke saare functions, constants , classes list kar deta ha

In [152]:
print(dir(np))

['ALLOW_THREADS', 'BUFSIZE', 'CLIP', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_builtins', '_distributor_init', '_financial_names', '_get_promotion_state', '_globals', '_int_extended_ms

In [153]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
print(dir(arr))  # arr object ke attribute and method dikhata ha

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__',

#### Spreadness / Dispertion of Data

    Range
    Std
    Var
    Quantiles

In [ ]:
# Dispertion --> data kitni baar faili hua ha