### Numpy In Python
#### Introduction to NumPy
In this , we are going to discuss a very important library called NumPy. Up to this point, we have covered advanced Python concepts such as iterators, generators, and decorators. Now, we are moving to a new module: data analysis with Python. Here, we will focus on libraries like NumPy, Pandas, and visualization libraries such as Matplotlib and Seaborn, which are fundamentally used for data analysis. Out of all these libraries, NumPy is extremely important, as it is also used in deep learning modules. With NumPy, we can create arrays, work with matrices, and perform mathematical operations very efficiently.

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


### Importing NumPy
To use NumPy, you need to import it. The common convention is to import it as np, which serves as an alias and allows you to use np. instead of typing numpy. everywhere.

In [2]:
import numpy as np

#### Creating Arrays
Let us create a one-dimensional array (1D array) using NumPy. We use the np.array function, which can take a list or tuple as input.

In [3]:
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

[1 2 3 4 5]


#### Array Type and Shape
Although the array may look like a list, it is actually a NumPy ndarray. You can check its type and shape using the following commands:

In [4]:
print(type(arr1))
print(arr1.shape)

<class 'numpy.ndarray'>
(5,)


#### Reshaping Arrays
If you want to convert a 1D array into a 2D array, you can use the reshape method. For example, reshaping to (1, 5) means one row and five columns. The total number of elements must remain the same.

In [5]:
arr2 = arr1.reshape(1, 5)
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]]
(1, 5)


#### Creating 2D Arrays Directly
You can also create a two-dimensional array directly by passing a nested list to np.array.

In [6]:
arr2 = np.array([[1, 2, 3, 4, 5], [2, 3, 4, 5, 6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


#### Using Inbuilt Functions to Create Arrays
NumPy provides several inbuilt functions to create arrays quickly, such as arange, ones, and eye.

In [7]:
arr = np.arange(0, 10, 2)
print(arr)
arr_reshaped = arr.reshape(5, 1)
print(arr_reshaped)

[0 2 4 6 8]
[[0]
 [2]
 [4]
 [6]
 [8]]
