### Numpy In Python
#### Introduction to NumPy
In this , we are going to discuss a very important library called NumPy. Up to this point, we have covered advanced Python concepts such as iterators, generators, and decorators. Now, we are moving to a new module: data analysis with Python. Here, we will focus on libraries like NumPy, Pandas, and visualization libraries such as Matplotlib and Seaborn, which are fundamentally used for data analysis. Out of all these libraries, NumPy is extremely important, as it is also used in deep learning modules. With NumPy, we can create arrays, work with matrices, and perform mathematical operations very efficiently.

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


### Importing NumPy
To use NumPy, you need to import it. The common convention is to import it as np, which serves as an alias and allows you to use np. instead of typing numpy. everywhere.

In [2]:
import numpy as np

#### Creating Arrays
Let us create a one-dimensional array (1D array) using NumPy. We use the np.array function, which can take a list or tuple as input.

In [3]:
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

[1 2 3 4 5]


#### Array Type and Shape
Although the array may look like a list, it is actually a NumPy ndarray. You can check its type and shape using the following commands:

In [4]:
print(type(arr1))
print(arr1.shape)

<class 'numpy.ndarray'>
(5,)


#### Reshaping Arrays
If you want to convert a 1D array into a 2D array, you can use the reshape method. For example, reshaping to (1, 5) means one row and five columns. The total number of elements must remain the same.

In [5]:
arr2 = arr1.reshape(1, 5)
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]]
(1, 5)


#### Creating 2D Arrays Directly
You can also create a two-dimensional array directly by passing a nested list to np.array.

In [6]:
arr2 = np.array([[1, 2, 3, 4, 5], [2, 3, 4, 5, 6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


#### Using Inbuilt Functions to Create Arrays
NumPy provides several inbuilt functions to create arrays quickly, such as arange, ones, and eye.

In [7]:
arr = np.arange(0, 10, 2)
print(arr)
arr_reshaped = arr.reshape(5, 1)
print(arr_reshaped)

[0 2 4 6 8]
[[0]
 [2]
 [4]
 [6]
 [8]]


In [8]:
ones_arr = np.ones((3,4))
print(ones_arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [9]:
identify_matrix = np.eye(3,2)
print(identify_matrix)

[[1. 0.]
 [0. 1.]
 [0. 0.]]


### Array Attributes
NumPy arrays have several useful attributes such as shape, ndim, size, dtype, and itemsize.

In [10]:
arr = np.array([[1,2,3] , [4,5,6]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)

(2, 3)
2
6
int64
8


#### 🔢 3. arr.ndim
➡ Returns the number of dimensions of the array.
#### 4. arr.size
➡ Returns the total number of elements in the array. --> 2*3 =6 toatal element
#### 6. arr.itemsize
➡ Returns the size (in bytes) of each element in the array.

#### Vectorized Operations
NumPy supports vectorized operations, allowing you to perform element-wise arithmetic directly on arrays.

In [11]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])
print(arr1+arr2)
print(arr1-arr2)
print(arr1/arr2)
print(arr1*arr2)

[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[0.1 0.1 0.1 0.1 0.1]
[ 10  40  90 160 250]


#### Universal Functions
NumPy provides universal functions (ufuncs) that operate element-wise on arrays, such as sqrt, exp, sin, and log.

In [12]:
arr = np.array([1,2,3,4,5,6])
print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.log(arr))


[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


#### Array Slicing and Indexing
You can perform slicing and indexing operations on NumPy arrays, similar to Python lists, but with more power for multi-dimensional arrays.

In [13]:
arr = np.array([[1,2,3,4] ,[5,6,7,8],[9,10,11,12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


#### Accessing Elements and Slices
You can access elements using row and column indices. Indexing starts from zero. For example, to access the element in the first row and first column, use arr[0, 0]. To access subarrays, use slicing.

In [14]:
print(arr[0,0])
print(arr[1: , 2: ])
print(arr[1: , :2])
print(arr[1: , 1:3])

1
[[ 7  8]
 [11 12]]
[[ 5  6]
 [ 9 10]]
[[ 6  7]
 [10 11]]


#### Modifying Array Elements
You can modify elements or slices of a NumPy array by assigning new values.

In [15]:
arr[0,0] = 100
print(arr)
arr[1:, :] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


#### Statistical Operations and Normalization
NumPy provides functions for statistical operations such as mean, median, standard deviation, and variance. Normalization is a common operation where data is transformed to have a mean of zero and a standard deviation of one.

In [16]:
data = np.array([1, 2, 3, 4, 5])
mean = np.mean(data)
std = np.std(data)
normalized_data = (data - mean) / std
print(normalized_data)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [17]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))

5.5
5.5
2.8722813232690143
8.25


#### Logical Operations
NumPy allows you to perform logical operations on arrays. For example, you can check which elements are greater than a certain value and use the result to filter the array.

In [18]:
data = np.array([1,2,3,4,5,6,7,8,9,10])
print(data>5)
print(data[data>5])
print(data[(data >= 5) & (data <= 8)])

[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]
[5 6 7 8]


#### Conclusion
In this session, we discussed NumPy, including how to create, reshape, and manipulate arrays, perform vectorized and universal operations, slice and index arrays, modify elements, and apply statistical and logical operations. NumPy is a foundational tool for scientific computing and data analysis in Python, and its concepts will be used extensively in future lessons, including machine learning and data analysis with Pandas.

#### Key Takeaways
NumPy is a fundamental library for scientific computing in Python, providing support for arrays, matrices, and mathematical functions.
Arrays can be created, reshaped, and manipulated using various NumPy functions such as np.array, reshape, arange, ones, and eye.
NumPy supports vectorized operations, universal functions, and logical operations for efficient computation.
Array slicing, indexing, and modification are essential for data manipulation, and NumPy offers powerful tools for these tasks.